dist: precise
language: cpp

addons:
    apt:
        packages:
            - g++-4.9
            - g++-5
            - clang-3.7
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8

matrix:
    include:
#        - os: osx
#          compiler: clang
        - os: linux
          compiler: gcc
          env: COMPILER=g++-4.9
        - os: linux
          compiler: gcc
          env: COMPILER=g++-5
        - os: linux
          compiler: clang
          env: COMPILER=clang++-3.7

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
            mkdir -p cmake
            travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" |
                tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

script:
    - BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
    - mkdir -p "${BUILD_DIR}"
    - cd "${BUILD_DIR}"
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
      else
        cmake ..
      fi
    - make 
    - make test ARGS="-VV"
